# Generated by Django 3.2 on 2023-04-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=1, max_length=7, unique=True, verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
